### ISSUE TITLE
Enhanced

### ISSUE THREAD

**Issue by JZZZ1314** [viperyl/ComfyUI-BiRefNet#2]
Have you considered this project with the same author, which can be recognized by semantics mask?

https://github.com/ZhengPeng7/GCoNet_plus

**Comment by viperyl** [comment]
> Have you considered this project with the same author, which can be recognized by semantics mask?
> 
> https://github.com/ZhengPeng7/GCoNet_plus

of course, it looks good, hope i can handle it this week

**Comment by viperyl** [comment]
I pack GCoNet_plus, link here https://github.com/viperyl/ComfyUI-GCoNet-plus/tree/main

**Comment by wibur0620** [comment]
![屏幕截图 2024-03-25 040715](https://github.com/viperyl/ComfyUI-BiRefNet/assets/131615326/7ca73feb-baf3-49e5-a7e2-d71ee4f415bc)
It surprises me why your plugin runs in the same directory as another author's plugin

**Comment by viperyl** [comment]
> ![屏幕截图 2024-03-25 040715](https://private-user-images.githubusercontent.com/131615326/316338987-7ca73feb-baf3-49e5-a7e2-d71ee4f415bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjQwOTMsIm5iZiI6MTcxMTM2Mzc5MywicGF0aCI6Ii8xMzE2MTUzMjYvMzE2MzM4OTg3LTdjYTczZmViLWJhZjMtNDllNS1hN2UyLWQ3MWVlNGY0MTViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMDQ5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDJhMWM5ZjgwMjA3Y2RkYzNkZDhmMzk0YjRmZWU2N2FkNDA4ZmY4NzdlZjVkMTk3Y2MwNjdjMjdkY2UxNTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aEQEAyurNfsVcjp6YOrLiRUTsD_kYe8FMymYRQ8UQyo) It surprises me why your plugin runs in the same directory as another author's plugin

because i want to shift all of black magic in Fooocus to ComfyUI
