### ISSUE TITLE
Installed all but comfy not showing the node

### ISSUE THREAD

**Issue by jags111** [viperyl/ComfyUI-BiRefNet#3]
Hey. I installed all .. but comfy is not detecting the node or class or it is not showing. can you check the category of the node. Also can you add a workflow example using your nodes instead of screen shot as it will help to test if the nodes are loading. 
thanks

check this part of your code
```
RETURN_TYPES = ("MASK", )
    RETURN_NAMES = ("mask", )
    FUNCTION = "matting"
    CATEGORY = "Fooocus"
```

**Comment by viperyl** [comment]
> Hey. I installed all .. but comfy is not detecting the node or class or it is not showing. can you check the category of the node. Also can you add a workflow example using your nodes instead of screen shot as it will help to test if the nodes are loading. thanks
> 
> check this part of your code
> 
> ```
> RETURN_TYPES = ("MASK", )
>     RETURN_NAMES = ("mask", )
>     FUNCTION = "matting"
>     CATEGORY = "Fooocus"
> ```

I have attach an example workflow in workflow folders, please check it

**Comment by jags111** [comment]
awesome and thanks and worked like a charm.. super cool. May be next change can we have any control on the masking so it is very specific to the needs.. it is super clear and awesome.
