### ISSUE TITLE
1 bug need fix,please help

### ISSUE THREAD

**Issue by T8mars** [viperyl/ComfyUI-BiRefNet#4]
the node conflict with node:'[ComfyUI_UltimateSDUpscale](https://github.com/ssitu/ComfyUI_UltimateSDUpscale)'
![a1](https://github.com/viperyl/ComfyUI-BiRefNet/assets/96167788/1cf119ea-0616-4868-8275-470ec483bee9)
![a2](https://github.com/viperyl/ComfyUI-BiRefNet/assets/96167788/20db9503-a5cc-40bd-b47f-08162ff66ca5)

**Comment by toyxyz** [comment]
Same here!

**Comment by viperyl** [comment]
updated now

**Comment by T8mars** [comment]
thank, it have been fixed,I will recomend this node to ohters,it's very well,thanks again
